% MUS.PULSECLARITY 
% estimates tempo
%
% Copyright (C) 2017 Olivier Lartillot
% All rights reserved.
% License: New BSD License. See full text of the license in LICENSE.txt in
% the main folder of the MiningSuite distribution.

function varargout = pulseclarity(varargin)
    varargout = sig.operate('mus','pulseclarity',initoptions,...
                            @init,@aud.pulseclarity.main,@after,...
                            varargin,'plus','extensive');
end


%%
function options = initoptions
    options = aud.pulseclarity.options;
    
        reso.key = 'Resonance';
        reso.type = 'String';
        reso.choice = {'ToiviainenSnyder','vanNoorden',0,'off','no'};
        reso.default = 'ToiviainenSnyder';
    options.reso = reso;
end


function [x,type] = init(x,option)
    [x,type] = aud.pulseclarity.init(x,option,...
                                     @mus_tempo_frame,@mus_tempo_noframe);
end


function y = mus_tempo_frame(x,option,frame)
    y = mus.tempo(x,option.fea,'Method',option.envmeth,...
                    option.band,...
                    'Sum',option.sum,'Enhanced',option.enh,...
                    'Resonance',option.reso,'Smooth',option.aver,...
                    'HalfwaveDiff',option.diffhwr,...
                    'Lambda',option.lambda,...
                    'FilterbankType',option.fbtype,...
                    'FilterType',option.ftype,...
                    'Filterbank',option.fb,'Mu',option.mu,...
                    'Log',option.log,...
                    'Inc',option.inc,'Halfwave',option.hw,...
                    'Median',option.median(1),option.median(2),...
                    'Min',option.mi,'Max',option.ma,...
                    'Total',option.m,'Contrast',option.thr,...
                    'Frame','FrameSize',option.fsize.value,option.fsize.unit,...
                            'FrameHop',option.fhop.value,option.fhop.unit);
end


function y = mus_tempo_noframe(x,option)
    y = mus.tempo(x,option.fea,'Method',option.envmeth,...
                    option.band,...
                    'Sum',option.sum,'Enhanced',option.enh,...
                    'Resonance',option.reso,'Smooth',option.aver,...
                    'HalfwaveDiff',option.diffhwr,...
                    'Lambda',option.lambda,...
                    'FilterbankType',option.fbtype,...
                    'FilterType',option.ftype,...
                    'Filterbank',option.fb,'Mu',option.mu,...
                    'Log',option.log,...
                    'Inc',option.inc,'Halfwave',option.hw,...
                    'Median',option.median(1),option.median(2),...
                    'Min',option.mi,'Max',option.ma,...
                    'Total',option.m,'Contrast',option.thr);
end


function x = after(x,option)
end