function varargout = autocor(varargin)


if 0 %isnumeric(varargin{1})
    [options post] = sig.options(sig.Autocor.autocoroptions,varargin,...
                                'sig.autocor');
    varargout = {sig.Autocor(varargin{1},options.name,options.unit,...
                              options.sampling,options.start,options.dims)};
else
    varargout = sig.operate('sig','autocor',sig.Autocor.autocoroptions,...
                                            sig.Autocor.autocorinit,...
                                            sig.Autocor.autocormain,...
                                            varargin);
end