function varargout = spectrum(varargin)


if 0 %isnumeric(varargin{1})
    [options post] = sig.options(sig.Autocor.autocoroptions,varargin,...
                                'sig.autocor');
    varargout = {sig.Autocor(varargin{1},options.name,options.unit,...
                              options.sampling,options.start,options.dims)};
else
    varargout = sig.operate('sig','spectrum',sig.Spectrum.spectrumoptions,...
                                             sig.Spectrum.spectruminit,...
                                             sig.Spectrum.spectrummain,...
                                             varargin,'sum');
end